### ISSUE TITLE
Blocking Cross Origin API request

### ISSUE THREAD

**Issue by hderoca** [googlecolab/jupyter_http_over_ws#17]
Hi, I'm having trouble connecting to local runtime. This is the error I am getting: 

    `(base) C:\Users\harol>jupyter notebook \ -- 
     NotebookApp.allow_origin='https://colab.research.google.com'\ --port=8888 \ -- 
     NotebookApp.port_retries=0 --no-browser`

    jupyter_http_over_ws extension initialized. Listening on /http_over_websocket
    [I 01:29:45.989 NotebookApp] JupyterLab extension loaded from 
    C:\Users\harol\anaconda3\lib\site-packages\jupyterlab
    [I 01:29:45.989 NotebookApp] JupyterLab application directory is 
    C:\Users\harol\anaconda3\share\jupyter\lab
    [I 01:29:46.005 NotebookApp] Serving notebooks from local directory: C:\
    [I 01:29:46.006 NotebookApp] The Jupyter 

I've followed the instructions in setting it  up and browsed all of the issues if I have similar issues. 

Any suggestions are greatly appreciated. Thanks

**Comment by JAYANTH-MOHAN** [comment]
jupyter notebook --NotebookApp.allow_origin='https://colab.research.google.com' \
  --port=9090 --no-browser



use this hope this would solve the issue

**Comment by eneugut** [comment]
Thank you!!
